gearfound-item-mongo:
  image: mongo
  ports:
    - "27017:27017"
    
gearfound-item-service:
  image: com.gearfound/gearfound-item-service
  ports:
    - "8100:8100"
  links:
    - gearfound-item-mongo

gearfound-api-gateway:
  image: com.gearfound.apigateway/gearfound-api-gateway
  ports:
    - "8080:8080"
  links:
    - gearfound-item-service
