version: "3"
networks:
  db-network:
  service-network:
    
services:
  gearfound-item-mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - db-network

  gearfound-authorization-mongo:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - db-network

  gearfound-authorization-service:
    image: com.gearfound/gearfound-authorization-service
    ports:
      - "8090:8090"
    networks:
      - db-network
      - service-network
    depends_on:
      - gearfound-authorization-mongo

  gearfound-item-service:
    image: com.gearfound/gearfound-item-service
    ports:
      - "8100:8100"
    networks:
      - db-network
      - service-network
    depends_on:
      - gearfound-item-mongo
      - gearfound-authorization-service

  gearfound-api-gateway:
    image: com.gearfound/gearfound-api-gateway
    ports:
      - "8080:8080"
    networks:
      - service-network
    depends_on:
      - gearfound-item-service
      - gearfound-authorization-service
