gearfound-item-mongo:
  image: mongo
  ports:
    - "27017:27017"

gearfound-authorization-mongo:
  image: mongo
  ports:
    - "27018:27017"

gearfound-authorization-service:
  image: com.gearfound/gearfound-authorization-service
  ports:
    - "8090:8090"
  links:
    - gearfound-authorization-mongo

gearfound-item-service:
  image: com.gearfound/gearfound-item-service
  ports:
    - "8100:8100"
  links:
    - gearfound-item-mongo
    - gearfound-authorization-service

gearfound-api-gateway:
  image: com.gearfound/gearfound-api-gateway
  ports:
    - "8080:8080"
  links:
    - gearfound-item-service
    - gearfound-authorization-service
